shepherd_milestone:
  task: push_default
  run:
    steps: 1000000
    envs: 1
    train_ratio: 512
    log_every: 30
    report_every: 120
    save_every: 300
  batch_size: 16
  batch_length: 64
  replay:
    size: 1e5
    online: True
  .*\.rssm: {deter: 512, hidden: 128, classes: 8}
  .*\.depth: 4
  .*\.units: 128
